<?php
/**
 * CreateUserIconBase64Request
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Supla\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SUPLA Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.03
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Supla\ApiClient\Model;

use \ArrayAccess;
use \Supla\ApiClient\ObjectSerializer;

/**
 * CreateUserIconBase64Request Class Doc Comment
 *
 * @category Class
 * @package  Supla\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateUserIconBase64Request implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'createUserIconBase64_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'function' => 'string',
        'sourceIcon' => 'int',
        'image1' => 'string',
        'image2' => 'string',
        'image3' => 'string',
        'image4' => 'string',
        'imageDark1' => 'string',
        'imageDark2' => 'string',
        'imageDark3' => 'string',
        'imageDark4' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'function' => null,
        'sourceIcon' => null,
        'image1' => 'byte',
        'image2' => 'byte',
        'image3' => 'byte',
        'image4' => 'byte',
        'imageDark1' => 'byte',
        'imageDark2' => 'byte',
        'imageDark3' => 'byte',
        'imageDark4' => 'byte'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'function' => false,
        'sourceIcon' => false,
        'image1' => false,
        'image2' => false,
        'image3' => false,
        'image4' => false,
        'imageDark1' => false,
        'imageDark2' => false,
        'imageDark3' => false,
        'imageDark4' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'function' => 'function',
        'sourceIcon' => 'sourceIcon',
        'image1' => 'image1',
        'image2' => 'image2',
        'image3' => 'image3',
        'image4' => 'image4',
        'imageDark1' => 'imageDark1',
        'imageDark2' => 'imageDark2',
        'imageDark3' => 'imageDark3',
        'imageDark4' => 'imageDark4'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'function' => 'setFunction',
        'sourceIcon' => 'setSourceIcon',
        'image1' => 'setImage1',
        'image2' => 'setImage2',
        'image3' => 'setImage3',
        'image4' => 'setImage4',
        'imageDark1' => 'setImageDark1',
        'imageDark2' => 'setImageDark2',
        'imageDark3' => 'setImageDark3',
        'imageDark4' => 'setImageDark4'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'function' => 'getFunction',
        'sourceIcon' => 'getSourceIcon',
        'image1' => 'getImage1',
        'image2' => 'getImage2',
        'image3' => 'getImage3',
        'image4' => 'getImage4',
        'imageDark1' => 'getImageDark1',
        'imageDark2' => 'getImageDark2',
        'imageDark3' => 'getImageDark3',
        'imageDark4' => 'getImageDark4'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('function', $data ?? [], null);
        $this->setIfExists('sourceIcon', $data ?? [], null);
        $this->setIfExists('image1', $data ?? [], null);
        $this->setIfExists('image2', $data ?? [], null);
        $this->setIfExists('image3', $data ?? [], null);
        $this->setIfExists('image4', $data ?? [], null);
        $this->setIfExists('imageDark1', $data ?? [], null);
        $this->setIfExists('imageDark2', $data ?? [], null);
        $this->setIfExists('imageDark3', $data ?? [], null);
        $this->setIfExists('imageDark4', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets function
     *
     * @return string|null
     */
    public function getFunction()
    {
        return $this->container['function'];
    }

    /**
     * Sets function
     *
     * @param string|null $function function
     *
     * @return self
     */
    public function setFunction($function)
    {
        if (is_null($function)) {
            throw new \InvalidArgumentException('non-nullable function cannot be null');
        }
        $this->container['function'] = $function;

        return $this;
    }

    /**
     * Gets sourceIcon
     *
     * @return int|null
     */
    public function getSourceIcon()
    {
        return $this->container['sourceIcon'];
    }

    /**
     * Sets sourceIcon
     *
     * @param int|null $sourceIcon ID of an existing user icon to replace with these new files. Optional.
     *
     * @return self
     */
    public function setSourceIcon($sourceIcon)
    {
        if (is_null($sourceIcon)) {
            throw new \InvalidArgumentException('non-nullable sourceIcon cannot be null');
        }
        $this->container['sourceIcon'] = $sourceIcon;

        return $this;
    }

    /**
     * Gets image1
     *
     * @return string|null
     */
    public function getImage1()
    {
        return $this->container['image1'];
    }

    /**
     * Sets image1
     *
     * @param string|null $image1 image1
     *
     * @return self
     */
    public function setImage1($image1)
    {
        if (is_null($image1)) {
            throw new \InvalidArgumentException('non-nullable image1 cannot be null');
        }
        $this->container['image1'] = $image1;

        return $this;
    }

    /**
     * Gets image2
     *
     * @return string|null
     */
    public function getImage2()
    {
        return $this->container['image2'];
    }

    /**
     * Sets image2
     *
     * @param string|null $image2 image2
     *
     * @return self
     */
    public function setImage2($image2)
    {
        if (is_null($image2)) {
            throw new \InvalidArgumentException('non-nullable image2 cannot be null');
        }
        $this->container['image2'] = $image2;

        return $this;
    }

    /**
     * Gets image3
     *
     * @return string|null
     */
    public function getImage3()
    {
        return $this->container['image3'];
    }

    /**
     * Sets image3
     *
     * @param string|null $image3 image3
     *
     * @return self
     */
    public function setImage3($image3)
    {
        if (is_null($image3)) {
            throw new \InvalidArgumentException('non-nullable image3 cannot be null');
        }
        $this->container['image3'] = $image3;

        return $this;
    }

    /**
     * Gets image4
     *
     * @return string|null
     */
    public function getImage4()
    {
        return $this->container['image4'];
    }

    /**
     * Sets image4
     *
     * @param string|null $image4 image4
     *
     * @return self
     */
    public function setImage4($image4)
    {
        if (is_null($image4)) {
            throw new \InvalidArgumentException('non-nullable image4 cannot be null');
        }
        $this->container['image4'] = $image4;

        return $this;
    }

    /**
     * Gets imageDark1
     *
     * @return string|null
     */
    public function getImageDark1()
    {
        return $this->container['imageDark1'];
    }

    /**
     * Sets imageDark1
     *
     * @param string|null $imageDark1 imageDark1
     *
     * @return self
     */
    public function setImageDark1($imageDark1)
    {
        if (is_null($imageDark1)) {
            throw new \InvalidArgumentException('non-nullable imageDark1 cannot be null');
        }
        $this->container['imageDark1'] = $imageDark1;

        return $this;
    }

    /**
     * Gets imageDark2
     *
     * @return string|null
     */
    public function getImageDark2()
    {
        return $this->container['imageDark2'];
    }

    /**
     * Sets imageDark2
     *
     * @param string|null $imageDark2 imageDark2
     *
     * @return self
     */
    public function setImageDark2($imageDark2)
    {
        if (is_null($imageDark2)) {
            throw new \InvalidArgumentException('non-nullable imageDark2 cannot be null');
        }
        $this->container['imageDark2'] = $imageDark2;

        return $this;
    }

    /**
     * Gets imageDark3
     *
     * @return string|null
     */
    public function getImageDark3()
    {
        return $this->container['imageDark3'];
    }

    /**
     * Sets imageDark3
     *
     * @param string|null $imageDark3 imageDark3
     *
     * @return self
     */
    public function setImageDark3($imageDark3)
    {
        if (is_null($imageDark3)) {
            throw new \InvalidArgumentException('non-nullable imageDark3 cannot be null');
        }
        $this->container['imageDark3'] = $imageDark3;

        return $this;
    }

    /**
     * Gets imageDark4
     *
     * @return string|null
     */
    public function getImageDark4()
    {
        return $this->container['imageDark4'];
    }

    /**
     * Sets imageDark4
     *
     * @param string|null $imageDark4 imageDark4
     *
     * @return self
     */
    public function setImageDark4($imageDark4)
    {
        if (is_null($imageDark4)) {
            throw new \InvalidArgumentException('non-nullable imageDark4 cannot be null');
        }
        $this->container['imageDark4'] = $imageDark4;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


